### ISSUE TITLE
Adds support for Composer v2

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-dependency-plugin#13]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | maybe ?

#### Summary

Composer v2 is behind the corner and we should be ready on the day 0, so we need updte this library ASAP.

This PR might be helpful:
https://github.com/Ocramius/PackageVersions/pull/133

**Comment by samsonasik** [comment]
@michalbundyra I created PR #14 for it

**Comment by ihor-sviziev** [comment]
@boesing I see we still don't have any stable version that supports composer v2. Is there any reason for not releasing stable version  that supports it?

**Comment by boesing** [comment]
@ihor-sviziev that is because this plugin is quite complex and I'd like to have some Users who are using the plugin in the Alpha in order to provide some Feedback. There are so many different projects and scenarios out there that I am unsure to mark this current state as stable as I changed pretty much everything in here.

The alpha can be used for composer v2, that should be totally fine until you are experiencing issues. If so, please Report back. If not, thats good news 👍🏻
