### ISSUE TITLE
v2.3.0 can't be installed with composer 2.3.0

### ISSUE THREAD

**Issue by evs-xsarus** [laminas/laminas-dependency-plugin#46]
De require voor de composer-plugin-api in v2.3.0 is more strict then it was in v2.2.0:

v2.2.0:
> "composer-plugin-api": "^1.1 || ^2.0",

v2.3.0:
> "composer-plugin-api": ">=1.1.0 <2.3.0",

This gives issues because v2.3.0 can't be installed. Could this be reverted, or, if there is a reason for this lock-in, could it be explained?

**Comment by Ocramius** [comment]
Composer 2.2.x is "LTS", while future 2.x will keep breaking BC in minor details.

Since the dependency plugin is in security-only mode, we won't be updating it to support newer versions of composer (and the associated breakages), so we pinned the dependency range.

See also https://github.com/laminas/technical-steering-committee/blob/8e29efc15e72de3881866c9de617777b0432a0ac/meetings/minutes/2022-07-11-TSC-Minutes.md#future-of-the-migration-layer

Docs around this could indeed be better 👍

**Comment by evs-xsarus** [comment]
Thank you for that explanation, it sounds reasonable. Since I'm installing Magento 2.4.4 which requires this package, I'll stick with v2.2.0 until Magento updates again .
